import { loadPlaywright, chromiumPath, sleep } from "./pw.mjs";
const { chromium } = loadPlaywright();
const b = await chromium.launch({ headless: true, executablePath: chromiumPath() });
const p = await (await b.newContext({ viewport: { width: 1280, height: 720 } })).newPage();
await p.goto("http://localhost:3000", { waitUntil: "load", timeout: 60000 });
await sleep(5000);
await p.getByRole("radio", { name: /Before/ }).click();
await sleep(1500);
const tue = p.getByRole("region", { name: /Tuesday/ });
console.log("=== BEFORE Tuesday ===\n" + (await tue.ariaSnapshot()).slice(0, 4000));
await tue.scrollIntoViewIfNeeded(); await p.screenshot({ path: "../out/inspect-before-tue.png" });
const html = await tue.evaluate(e => e.outerHTML.slice(0, 3000)); console.log(html);
await p.getByRole("radio", { name: /After/ }).click(); await sleep(1000);
const g = p.getByRole("region", { name: /Monday/ }).getByRole("group").first();
console.log("=== group html ===\n" + (await g.evaluate(e => e.outerHTML.slice(0, 1500))));
await p.getByRole("tab", { name: /Activity/ }).click(); await sleep(2000);
console.log("=== ACTIVITY ===\n" + (await p.locator("body").ariaSnapshot()).slice(0, 5000));
await p.screenshot({ path: "../out/inspect-activity.png" });
await p.getByRole("tab", { name: /Plan/ }).click(); await sleep(1000);
await p.getByRole("radio", { name: "Demo" }).click(); await sleep(3000);
console.log("=== DEMO ===\n" + (await p.locator("body").ariaSnapshot()).slice(0, 8000));
await p.screenshot({ path: "../out/inspect-demo.png" });
await p.getByRole("radio", { name: "Live" }).click(); await sleep(1000);
await b.close();
